apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: saas-provisioning-demo
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: saas-provisioning-demo
  service:
    name: saas-provisioning-demo
    port: 80
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: allow
      methods:
        - PUT
        - DELETE
