apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: saas-provisioning-demo-bind
  labels:
    app: saas-provisioning-demo
spec:
  instanceRef:
    name: <Service Instance Name>
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: saas-provisioning-demo-bind-usage
  labels:
    app: saas-provisioning-demo
spec:
  serviceBindingRef:
    name: saas-provisioning-demo-bind
  usedBy:
    kind: deployment
    name: saas-provisioning-demo
  parameters:
    envPrefix:
      name: "IDP_"