apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: cc-sample
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: allow
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - HEAD
    path: /.*
  service:
    host: cc-sample
    name: cc-sample
    port: 80
