apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: cc-sample
spec:
  buildResources:
    limits:
      cpu: 1700m
      memory: 1100Mi
    requests:
      cpu: 1100m
      memory: 1100Mi
  deps: "{ \n  \"name\": \"cc-sample\",\n  \"version\": \"1.0.0\",\n  \"dependencies\":
    {\n    \"axios\": \"0.21.4\"\n  }\n}"
  env:
  - name: cc_url
    value: http://localhost:3000/orders?OrderNo=123
  labels:
    use-6820b74f-b0f2-4ccb-a370-160e8edc22c6: "71762"
  maxReplicas: 5
  minReplicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  runtime: nodejs14
  source: |
    const axios = require("axios");

    module.exports = {
      main: async function (event, context) {
        try {
          const body = {
            somedata: "1234",
          };

          var result = await axios.get(process.env.cc_url, {
            headers: {
              "Content-Type": "application/json",
              "SAP-Connectivity-SCC-Location_ID": "",
            },
            proxy: {
              protocol: "http",
              host: "connectivity-proxy.kyma-system.svc.cluster.local",
              port: 20003,
            },
          });
          return result.data;
        } catch (error) {
          console.log("an error occurred: ", error);
          return "an error occurred...";
        }
      },
    };