apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: alert-notif-ser-instance
spec:
  serviceOfferingName: alert-notification
  servicePlanName: standard
  parameters:
    configuration:
      actions:
      - name: email
        properties:
          destination: {{ .Values.alertnotification.email | b64dec }}
        state: ENABLED
        type: EMAIL
      conditions:
      - name: system_down_condition
        predicate: EQUALS
        propertyKey: eventType
        propertyValue: system_down_condition
      subscriptions:
      - actions:
        - email
        conditions:
        - system_down_condition
        name: system_down_condition
        state: ENABLED
---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: alert-notif
spec:
  env:
  - name: oauth_url
    valueFrom:
      secretKeyRef:
        key: oauth_url
        name: alert-notif-ser-binding
  - name: client_id
    valueFrom:
      secretKeyRef:
        key: client_id
        name: alert-notif-ser-binding
  - name: client_secret
    valueFrom:
      secretKeyRef:
        key: client_secret
        name: alert-notif-ser-binding
  - name: CLUSTER_DOMAIN
    value: {{ .Values.alertnotification.clusterdomain | b64dec }}
  - name: url
    value: {{ .Values.alertnotification.url | b64dec }}
  deps: "{ \n  \"name\": \"alert-notif-test\",\n  \"version\": \"1.0.0\",\n  \"dependencies\":
    {\n    \"@sap_oss/alert-notification-client\": \"1.1.0\"\n  }\n}"
  runtime: nodejs14
  source: >-
    const { OAuthAuthentication, AlertNotificationClient, BasicAuthentication,
        RegionUtils, Severity, Category } = require("@sap_oss/alert-notification-client");
    const { Region, Platform } =
    require("@sap_oss/alert-notification-client/dist/utils/region");


    const oAuthAuthentication = new OAuthAuthentication({
        username: process.env.client_id,
        password: process.env.client_secret,
        oAuthTokenUrl: process.env.oauth_url
    });

    module.exports = {
      main: async function (event, context) {
          try{
            const client = new AlertNotificationClient({
                authentication: oAuthAuthentication,
                region: new Region(Platform.CF, process.env.url),
            });
            const result =  await processAlert(client, event.data);
            return JSON.stringify(result);
          }catch(error){
              console.log(error);
              return error;
          };
      }
    }

    async function processAlert(client, data){
        const cur_time = Math.floor(+new Date() / 1000);
        return await client.sendEvent({
            body: 'The chatbot crashed. \nDETAILS:' + JSON.stringify(data).replace(/[{}]|,/g, "\n"),
            subject: 'Chatbot crash',
            eventType: 'system_down_condition',
            severity: Severity.FATAL,
            category: Category.ALERT,
            eventTimestamp: cur_time,
            priority: 1
        });
    }



---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: alert-notif-ser-binding
spec:
  serviceInstanceName: alert-notif-ser-instance