apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcorderserver
  labels:
    app: grpcorderserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcorderserver
  template:
    metadata:
      labels:
        app: grpcorderserver
    spec:
      containers:
      - name: grpcorderserver
        image: jcawley5/grpcorderserver
        env:
        - name: _GRPC_TOKEN_
          value: "12345678"
        ports:
        - name: grpc
          containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpcorderserver
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
  selector:
    app: grpcorderserver
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpcorderserver
spec:
  gateways:
  - kyma-gateway.kyma-system.svc.cluster.local
  hosts:
  - 'grpcorderserver.a0e7f99.kyma.shoot.live.k8s-hana.ondemand.com'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: grpcorderserver.grpc.svc.cluster.local
        port:
          number: 50051