apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: cpi-scc-httpbin
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: cpi-scc-httpbin
    name: cpi-scc-httpbin
    port: 80