apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: sentiment-analysis
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.internal.product.reviewsubmitted.v1
  sink: http://sentiment-analysis.sentiment-analysis.svc.cluster.local
