apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: grpcorderserver
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: allow
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
  service:
    host: grpcorderserver
    name: grpcorderserver
    port: 50051