apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: alert-notif-ser-instance
spec:
  serviceOfferingName: alert-notification
  servicePlanName: standard
  parameters:
    configuration:
      actions:
      - name: email
        properties:
          destination: {{ .Values.alertnotification.email | b64dec }}
        state: ENABLED
        type: EMAIL
      - name: slack
        properties:
          destination: {{ .Values.alertnotification.slack.webhook | b64dec }}
        state: ENABLED
        type: SLACK
      conditions:
      - name: system_down_condition
        predicate: EQUALS
        propertyKey: eventType
        propertyValue: system_down_condition
      subscriptions:
      - actions:
        - slack
        conditions:
        - system_down_condition
        name: system_down_condition
        state: ENABLED
---
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: alert-notif
spec:
  runtime: nodejs16
  source:
    gitRepository:
      url: https://github.com/SAP-samples/kyma-runtime-extension-samples.git
      baseDir: /chatbot-conversational_AI/alert-notif/function
      reference: main
  env:
  - name: oauth_url
    valueFrom:
      secretKeyRef:
        key: oauth_url
        name: alert-notif-ser-binding
  - name: client_id
    valueFrom:
      secretKeyRef:
        key: client_id
        name: alert-notif-ser-binding
  - name: client_secret
    valueFrom:
      secretKeyRef:
        key: client_secret
        name: alert-notif-ser-binding
  - name: CLUSTER_DOMAIN
    value: {{ .Values.alertnotification.clusterdomain | b64dec }}
  - name: url
    value: {{ .Values.alertnotification.url | b64dec }}
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: alert-notif-ser-binding
spec:
  serviceInstanceName: alert-notif-ser-instance