apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: sample-ldap
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
      path: /.*
  service:
    host: sample-ldap
    name: sample-ldap
    port: 8080