apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
  labels:
    app: bot-secret
type: Opaque
stringData:
  cai-credentials-id: xxxxxxxxx
  cai-credentials-secret: xxxxxxxxx
  #bot-url: {user_slug}/bots/{bot_slug}/versions/{version_slug}/qna/topic/knowledge_sources/{knowledge_source_id}/answers
  bot-url:  xxxxxxxxxxx/bots/xxxxxxxxxx/versions/xxxxxxxxxxxxxx/qna/topic/knowledge_sources/xxxxxxxxxxxxxxxxxxxxx/answers
  cai-x-token: xxxxxxxxx
  stack-tag: kyma-runtime
  stack-key: xxxxxxxxx
  db-name: BotKnowledgeDB
  db-host: mssql.chatbot.svc.cluster.local
  db-username: sa
  db-password: mfrCPTK3