---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-extension-java
    kyma-grafana: enabled
  name: sample-extension-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-extension-java
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-extension-java
        kyma-grafana: enabled
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
      - image: gauravsap/sample-extension-java:0.0.22
        name: sample-extension-java
        ports:
          - containerPort: 8080
        envFrom:
          - secretRef:
              name: sample-extension-java
              optional: true
        resources:
          requests:
            memory: 1024M
            cpu: 200m
          limits:
            memory: 1024M
            cpu: 500m
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmp
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-extension-java
  name: sample-extension-java
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sample-extension-java
  type: ClusterIP
status:
  loadBalancer: {}
