apiVersion: v1
kind: ConfigMap
metadata:
  name: app-auth-proxy
  labels:
    app: app-auth-proxy
data:
  config.json: |
    {
      "routes": [{
              "path": "/anything",
              "priority": 10,
              "protected": true,
              "remove_from_path": "",
              "target": "http://httpbin.saas:8000"
          }],
      "token_endpoint_auth_method": "client_secret_post",
      "redirect_uri": "https://app-auth-proxy.c-6d073c0.kyma-stage.shoot.live.k8s-hana.ondemand.com/oauth/callback",
      "debug": true,
      "redis_store": {
        "addr": "",
        "password": "",
        "db": 0
      },
      "cookie":{
          "session_name": "sample-session",
          "max_age_seconds": 900,
          "key": "asecurekeyvalue",
          "httponly": true
      }
    }