
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-provisioning-demo
  labels:
    app: saas-provisioning-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-provisioning-demo
  template:
    metadata:
      labels:
        app: saas-provisioning-demo
    spec:
      containers:
        # replace the repository URL with your own repository
        - image: jcawley5/saas-provisioning-demo:latest
          imagePullPolicy: Always
          name: saas-provisioning-demo
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: AppURL
              valueFrom:
                configMapKeyRef:
                  name: saas-provisioning-demo
                  key: AppURL
      volumes:
        - name: config-volume
          configMap:
            name: saas-provisioning-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: saas-provisioning-demo
  labels:
    app: saas-provisioning-demo
data:
  AppURL: https://saas-provisioning-demo.<cluster domain>/anything
---
apiVersion: v1
kind: Service
metadata:
  name: saas-provisioning-demo
  labels:
    app: saas-provisioning-demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: saas-provisioning-demo
