apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: bot-observer-apirule
spec:
  gateway: {{ .Values.bot.botobservertool.apirule.gateway }}
  host: bot-observer
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    path: /.*
    service:
      name: bot-observer-service
      port: {{ .Values.bot.botobservertool.apirule.port }}
