apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: api-mssql-function
  labels:
    app: api-mssql-function
spec:
  runtime: nodejs16
  source:
    gitRepository:
      url: https://github.com/SAP-samples/kyma-runtime-extension-samples.git
      baseDir: /chatbot-conversational_AI/knowledge-database/api-mssql-function/function
      reference: main
  env:
    - name: database
      value: {{ .Values.apimssqlfunction.deployment.env.database }}
    - name: host
      value: {{ .Values.apimssqlfunction.deployment.env.host }}
    - name: password
      value: {{ .Values.apimssqlfunction.deployment.env.password }}
    - name: username
      value: {{ .Values.apimssqlfunction.deployment.env.username }}
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: api-mssql-function
spec:
  gateway: {{ .Values.apimssqlfunction.apirule.gateway }}
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - DELETE
  service:
    host: api-mssql-function
    name: api-mssql-function
    port: 80
