name: Build docker sample-extension-dotnet-minimalapi

on:
  push:
    branches: [ main ]
    paths:
    - "sample-extension-dotnet-minimalapi/**"
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: 'Build .NET Project'
      shell: bash
      run: |
        pushd './sample-extension-dotnet-minimalapi/TodoApi'
        dotnet publish -c Release
        popd     
    - name: Build the Docker image
      shell: bash
      run: |
        pushd './sample-extension-dotnet-minimalapi/'
        make build-image
        popd
