name: build-and-publish

on:
  release:
    types: [published]
  workflow_dispatch: {}
env:
  REGISTRY: ghcr.io
  SUBDIRECTORY: custom-component-dapr
  IMAGE_NAME: daprwishlistapp
  LABEL: 1.0.0

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry (GH Packages)
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.SUBDIRECTORY }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository}}/${{ env.IMAGE_NAME }}:${{ env.LABEL }}
          labels: ${{ steps.meta.outputs.labels }}            
