name: Build docker sample-extension-java

on:
  push:
    branches: [ main ]
    paths:
    - "sample-extension-java/**"
  workflow_dispatch:

jobs:

  build:
    defaults:
      run:
        working-directory: sample-extension-java
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.5.0
      with:
        java-version: 17
        distribution: jdk
    - name: Gradle Build and then Build the Docker image
      run: make build-image
